import { readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const [predText, objText] = await Promise.all([
  readFile(join(root, "predicate-nicknames.jsonl"), "utf-8"),
  readFile(join(root, "object-nicknames.jsonl"), "utf-8"),
]);

const output = `// AUTO-GENERATED by build-data.ts — do not edit
import type { WordEntry } from "../../src/types.js";

export const predicates: WordEntry[] = ${JSON.stringify(
  predText
    .split("\n")
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l)),
)};

export const objects: WordEntry[] = ${JSON.stringify(
  objText
    .split("\n")
    .filter((l) => l.trim())
    .map((l) => JSON.parse(l)),
)};
`;

await writeFile(join(__dirname, "src", "data.ts"), output);
console.log("Generated worker/src/data.ts");
